apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: groupresourcequotaenforcers.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: GroupResourceQuotaEnforcer
    listKind: GroupResourceQuotaEnforcerList
    plural: groupresourcequotaenforcers
    singular: groupresourcequotaenforcer
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GroupResourceQuotaEnforcer is the Schema for the groupresourcequotaenforcers
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GroupResourceQuotaEnforcerSpec defines the desired state of
            GroupResourceQuotaEnforcer
          properties:
            imageRegistry:
              description: ImageRegistry is the image repository
              type: string
          required:
          - imageRegistry
          type: object
        status:
          description: GroupResourceQuotaEnforcerStatus defines the observed state
            of GroupResourceQuotaEnforcer
          properties:
            nodes:
              description: Nodes are the names of the grq pods
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
