apiVersion: operator.ibm.com/v1alpha1
kind: GroupResourceQuotaEnforcer
metadata:
  name: example-grqenforcer
spec:
  imageRegistry: quay.io/opencloudio
  instanceNamespace: services
  certSecret: cert-secret
